# Generated by Django 3.0.8 on 2020-07-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
