# Generated by Django 3.0.8 on 2020-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200721_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=25, null=True)),
                ('otp_number', models.CharField(max_length=7, null=True)),
            ],
        ),
    ]
