# Generated by Django 3.0.8 on 2020-07-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_otpnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpnumber',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='otpnumber',
            name='otp_number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
