# Generated by Django 3.0.8 on 2020-07-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200723_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpnumber',
            old_name='count',
            new_name='counts',
        ),
    ]
