# Generated by Django 3.0.8 on 2020-07-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200723_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpnumber',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
