# Generated by Django 3.0.8 on 2020-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200728_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
