# Generated by Django 3.0.8 on 2020-07-14 12:25

import app_base.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('eng_name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('primary_price', models.PositiveIntegerField(null=True)),
                ('primary_image', models.ImageField(null=True, upload_to=app_base.models.primary_image_path)),
                ('discount_status', models.BooleanField(default=False)),
                ('suggest', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Productdiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('data_status', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.ManyToManyField(blank=True, to='app_base.Category')),
            ],
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=app_base.models.image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_base.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productdiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.Productdiscount'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(to='app_base.Seller'),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, to='app_base.Category'),
        ),
        migrations.CreateModel(
            name='AttrarName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Attrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('attrarname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.AttrarName')),
            ],
        ),
    ]
