# Generated by Django 3.0.8 on 2020-07-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSpecifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.ManyToManyField(blank=True, to='app_base.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('generalspecifications', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.GeneralSpecifications')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specificationsvalue',
            field=models.ManyToManyField(to='app_base.SpecificationsValue'),
        ),
    ]
